### ISSUE TITLE
Updated version for Monterey?

### ISSUE THREAD

**Issue by dnadlinger** [apple-opensource/dyld#1]
Would it be possible to update the source dump here to the version shipped with macOS 12?

This would be particularly interesting as the `dladdr` behaviour appears to have changed, which now returns succeeds pointing to the base image on `dladdr((void*)-1, …);`.

**Comment by skissane** [comment]
It is available here: https://github.com/apple-oss-distributions/dyld/tree/dyld-960

I'm not sure why this unofficial (and out of date) mirror still exists, given that Apple themselves are now officially pushing their source code dumps to GitHub. It confuses a lot of people.
